### ISSUE TITLE
Odd mouse behaviour, seems resolution dependant

### ISSUE THREAD

**Issue by brunocar** [qndel/Infernity#11]
I have this wierd thing where the mouse is stuck to a square area that starts in the upper left part of the window, seems to happen even in fullscreen and changing the resolution doesnt fix it, but rather it seems to make the square smaller the bigger the resolution.

**Comment by qndel** [comment]
All things like this will get fixed when I rewrite infernity using DevilutionX :)

**Comment by brunocar** [comment]
What's the ETA on that? Also, what's the difference?

**Comment by qndel** [comment]
Cross platform etc., ETA probably 2 months or something

**Comment by brunocar** [comment]
oh damn, i guess in the meantime i'll hold off on that vanilla diablo run then, thanks!

**Comment by EtaYorius** [comment]
I'm having the same issue, i had to change the resolution but the game looked very pixelated and the characters kinda wide. I also had this issue where map was stuck to the upper left side of the screen, it sort of worked but parts of the map was outside my screen. I tried to centered the minimap but i could not make it work completely. I rather have the game with black boxes on the sides, sort of like GOG version.

Also, where would it be correct place to add some suggestions for Infernity?

**Comment by qndel** [comment]
@EtaYorius place for suggestions would be discord ;)

**Comment by brunocar** [comment]
this wasnt a suggestion though, it was a bug

**Comment by qndel** [comment]
yes but this issue is well known and you can find the fix for it on discord too :) @brunocar

**Comment by brunocar** [comment]
oh cool, i dont use discord though
