### ISSUE TITLE
DClicker not compatible

### ISSUE THREAD

**Issue by Lakuzia** [qndel/Infernity#12]
I like to save my hands and my mouse by using DClicker but I can't seem to get it to work with Infernity. 

File is here: https://freshmeat-blog.de.tl/Downloads.htm Laballed "Diablo Clicker" and with Windows 10 it's v3.1 in the package.

Either could you add an option in the mod to allow this function or make this compatibile?

**Comment by qndel** [comment]
I'm waiting for https://github.com/diasurgical/devilutionX so I can rewrite infernity:) so atm I'm not going to update the old version
