### ISSUE TITLE
Game UI is messed up

### ISSUE THREAD

**Issue by nandito104** [qndel/Infernity#15]
![image](https://user-images.githubusercontent.com/22856479/75918348-f4b2fa00-5e31-11ea-9775-4ba57b804100.png)

![image](https://user-images.githubusercontent.com/22856479/75918509-3cd21c80-5e32-11ea-9216-79ef1860f798.png)

As you probably can see in the picture, I can't get the game to run properly. The menu UI can be seen, as well as a screenshot of how the game itself looks.

**Comment by qndel** [comment]
looks like you got outdated ddraw.dll
