### ISSUE TITLE
Nothing Happens After Killing Diablo

### ISSUE THREAD

**Issue by fsdnotavai** [qndel/Infernity#19]
Is there supposed to be another difficulty? Diablo froze when killed, and nothing ever happens after that. I can return to town, or re-enter dungeon. No other difficulty option for starting a new game.

How to proceed to the next level?

**Comment by AJenbo** [comment]
Difficulty levels are unlocked via your hero level. After Diablo dies the end game movie should play. Please provide information about what system and version you are using.

**Comment by qndel** [comment]
> Is there supposed to be another difficulty? Diablo froze when killed, and nothing ever happens after that. I can return to town, or re-enter dungeon. No other difficulty option for starting a new game.
> 
> How to proceed to the next level?

Single or multi? Single doesn't let you change difficulty, to enjoy infernity's new difficulty, you need to play in multiplayer.
Iirc I disabled diablo triggering endgame cinematic because come on, we've all seen it already and it lets you pick items etc. without forcefully quitting the game.
